services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ml:
    build: ./ml
    ports:
      - "5001:5001"
  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ml
    env_file:
      - .env
volumes:
  postgres_data:
